#goal definition
int32 start
---
#result definition
std_msgs/String[] ids
geometry_msgs/Transform[] transforms
float32[] confidences
---
#feedback
std_msgs/String[] ids
geometry_msgs/Transform[] transforms
float32[] confidences

