#goal definition
int32 start
---
#result definition
std_msgs/String[] ids
float32[] confidences
geometry_msgs/Transform[] transforms
---
#feedback
std_msgs/String[] ids
float32[] confidences
geometry_msgs/Transform[] transforms
