#! /usr/bin/env python

import sys
import rospy
import actionlib

from sr_point_cloud.msg import *

if __name__ == '__main__':
    rospy.init_node('track_client')
    client = actionlib.SimpleActionClient(
            'point_cloud_tracker/track', TrackAction)
    client.wait_for_server()

    cmd = sys.argv[1]
    if not cmd:
        print "Usage: " + sys.argv[0] + " CMD"
        sys.exit(3)

    if cmd in ["centered", "nearest"]:
        goal = TrackGoal()
        goal.target = cmd
        client.send_goal(goal)
        #client.wait_for_result(rospy.Duration.from_sec(10.0))
        #client.cancel_goal()
    elif cmd in ["cancel", "stop"]:
        client.cancel_all_goals()
    else:
        print "Unknown command: " + cmd
        sys.exit(4)

