#!/usr/bin/env python
"""
See README.md
"""
import rospy
from sr_extrinsic_calibration.camera_calibration import CameraCalibration

if __name__ == "__main__":
    rospy.init_node("camera_calibration")
    camera_calibration = CameraCalibration()
    camera_calibration.start()
