#!/usr/bin/env python
"""
See README.md
"""
import rospy
from sr_extrinsic_calibration.camera_calibration import CameraCalibration

if __name__ == "__main__":
    rospy.init_node("print_camera_tf")
    camera_calibration = CameraCalibration()
    camera_calibration.run_once()
    camera_calibration.print_camera_tf()
